import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";
import NavigationBar from "@/components/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Sidebar />
      <NavigationBar />
      <main className="ml-[26rem] p-4">{children}</main>
    </>
  );
}
